import type { SettingDefinition } from "./settings";

export const CORE_SETTINGS: SettingDefinition[] = [
  {
    key: "core.share_location",
    group: "core",
    type: "string",
    label: "Download Location",
    description: "Root directory where downloaded files are saved",
    defaultValue: "./downloads",
    envVar: "SHARE_LOCATION",
    validation: { required: true },
    sortOrder: 0,
  },
  {
    key: "core.max_concurrent_downloads",
    group: "core",
    type: "number",
    label: "Max Concurrent Downloads",
    description: "Maximum number of downloads to process in parallel",
    defaultValue: 10,
    envVar: "MAX_CONCURRENT_DOWNLOADS",
    validation: { required: true, min: 1, max: 50 },
    sortOrder: 1,
  },
  {
    key: "notifications.ntfy_url",
    group: "notifications",
    type: "string",
    label: "ntfy URL",
    description: "ntfy.sh endpoint for push notifications (leave empty to disable)",
    defaultValue: "",
    envVar: "NTFY_URL",
    sortOrder: 0,
  },
  {
    key: "kavita.base_url",
    group: "kavita",
    type: "string",
    label: "Kavita Base URL",
    description: "URL of your Kavita server (e.g. http://localhost:5000)",
    defaultValue: "",
    envVar: "KAVITA_BASE_URL",
    sortOrder: 0,
  },
  {
    key: "kavita.api_key",
    group: "kavita",
    type: "password",
    label: "API Key",
    description: "Kavita API key for authentication",
    defaultValue: "",
    envVar: "KAVITA_API_KEY",
    sensitive: true,
    sortOrder: 1,
  },
  {
    key: "kavita.plugin_name",
    group: "kavita",
    type: "string",
    label: "Plugin Name",
    description: "Name used when authenticating with Kavita",
    defaultValue: "Downloader",
    envVar: "KAVITA_PLUGIN_NAME",
    sortOrder: 2,
  },
  {
    key: "kavita.library_id",
    group: "kavita",
    type: "string",
    label: "Library ID",
    description: "Kavita library ID to trigger scans on after downloads",
    defaultValue: "",
    envVar: "KAVITA_LIBRARY_ID",
    sortOrder: 3,
  },
  {
    key: "kavita.force_scan",
    group: "kavita",
    type: "boolean",
    label: "Force Scan",
    description: "Force a full rescan instead of incremental scan",
    defaultValue: false,
    envVar: "KAVITA_FORCE_SCAN",
    sortOrder: 4,
  },
  {
    key: "kavita.scan_delay_ms",
    group: "kavita",
    type: "number",
    label: "Scan Delay (ms)",
    description: "Delay in milliseconds before triggering library scan after download",
    defaultValue: 15000,
    envVar: "KAVITA_SCAN_DELAY_MS",
    validation: { min: 0, max: 300000 },
    sortOrder: 5,
  },
];
