@API_HostAddress = https://save.pauljoda.com

GET {{API_HostAddress}}/api/health/

### Test
POST {{API_HostAddress}}/api/download?url=https://archive.org/details/bcprips

###

# curl -X POST "https://yourdomain.com/manga/download?url=https://manga.com/manga/2"
POST {{API_HostAddress}}/manga/download?url=https://manga.com/manga/2

###



###


###
